# Generated by Django 3.0.3 on 2020-08-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_App', '0006_auto_20200809_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='category', max_length=264)),
                ('teacher_name', models.CharField(default='teacher_name', max_length=264)),
                ('questiona', models.CharField(default='question', max_length=264)),
                ('optiona1', models.CharField(default='opt1', max_length=264)),
                ('optiona2', models.CharField(default='opt2', max_length=264)),
                ('optiona3', models.CharField(default='opt3', max_length=264)),
                ('optiona4', models.CharField(default='opt4', max_length=264)),
                ('option_a_correct', models.CharField(default='opt_correct', max_length=264)),
                ('questionb', models.CharField(default='question', max_length=264)),
                ('optionb1', models.CharField(default='opt1', max_length=264)),
                ('optionb2', models.CharField(default='opt2', max_length=264)),
                ('optionb3', models.CharField(default='opt3', max_length=264)),
                ('optionb4', models.CharField(default='opt4', max_length=264)),
                ('option_b_correct', models.CharField(default='opt_correct', max_length=264)),
                ('questionc', models.CharField(default='question', max_length=264)),
                ('optionc1', models.CharField(default='opt1', max_length=264)),
                ('optionc2', models.CharField(default='opt2', max_length=264)),
                ('optionc3', models.CharField(default='opt3', max_length=264)),
                ('optionc4', models.CharField(default='opt4', max_length=264)),
                ('option_c_correct', models.CharField(default='opt_correct', max_length=264)),
                ('questiond', models.CharField(default='question', max_length=264)),
                ('optiond1', models.CharField(default='opt1', max_length=264)),
                ('optiond2', models.CharField(default='opt2', max_length=264)),
                ('optiond3', models.CharField(default='opt3', max_length=264)),
                ('optiond4', models.CharField(default='opt4', max_length=264)),
                ('option_d_correct', models.CharField(default='opt_correct', max_length=264)),
                ('questione', models.CharField(default='question', max_length=264)),
                ('optione1', models.CharField(default='opt1', max_length=264)),
                ('optione2', models.CharField(default='opt2', max_length=264)),
                ('optione3', models.CharField(default='opt3', max_length=264)),
                ('optione4', models.CharField(default='opt4', max_length=264)),
                ('option_e_correct', models.CharField(default='opt_correct', max_length=264)),
            ],
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
