# Generated by Django 3.0.3 on 2020-08-10 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_App', '0008_test_appeared_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='scores',
            field=models.TextField(blank=True),
        ),
    ]
