# Generated by Django 3.0.3 on 2020-08-10 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_App', '0009_test_scores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_pk', models.CharField(default='test', max_length=264)),
                ('username', models.CharField(default='username', max_length=264)),
                ('score', models.CharField(default='score', max_length=264)),
            ],
        ),
    ]
